import { db, collaboratorsTable } from "@workspace/db";
import { count } from "drizzle-orm";

const collaborators = [
  // ── Lendas Financeiras ─────────────────────────────────────────────────────
  {
    name: "Ana Beatriz Santos",
    role: "Diretora de Finanças",
    area: "Controladoria",
    management: "Finanças Corporativas",
    yearsAtVale: 18,
    rarity: "lendaria",
    category: "Lendas Financeiras",
    points: 100,
    isSpecial: false,
    superPower: "Visão Estratégica",
    achievement: "Reduziu custos operacionais em 30% em dois anos",
    curiosity: "Fala quatro idiomas e já trabalhou em três continentes",
  },
  {
    name: "Carlos Mendes",
    role: "CFO",
    area: "Alta Gestão",
    management: "Presidência",
    yearsAtVale: 22,
    rarity: "lendaria",
    category: "Lendas Financeiras",
    points: 150,
    isSpecial: false,
    superPower: "Liderança Transformacional",
    achievement: "Liderou a maior emissão de bonds da empresa",
    curiosity: "Ex-atleta de natação olímpica",
  },
  {
    name: "Fernanda Lima",
    role: "Gerente de Tesouraria",
    area: "Tesouraria",
    management: "Finanças Corporativas",
    yearsAtVale: 12,
    rarity: "epica",
    category: "Lendas Financeiras",
    points: 60,
    isSpecial: false,
    superPower: "Gestão de Liquidez",
    achievement: "Estruturou hedge cambial que economizou R$500M",
    curiosity: "Pilota avião nas horas vagas",
  },
  // ── Guardiões da Controladoria ─────────────────────────────────────────────
  {
    name: "Roberto Alves",
    role: "Controller Sênior",
    area: "Controladoria",
    management: "Finanças Corporativas",
    yearsAtVale: 9,
    rarity: "epica",
    category: "Guardiões da Controladoria",
    points: 50,
    isSpecial: false,
    superPower: "Fechamento Impecável",
    achievement: "Zero apontamentos em auditoria externa por 5 anos",
    curiosity: "Colecionador de moedas antigas de todo o mundo",
  },
  {
    name: "Juliana Costa",
    role: "Analista de Controladoria",
    area: "Controladoria",
    management: "Finanças Corporativas",
    yearsAtVale: 4,
    rarity: "rara",
    category: "Guardiões da Controladoria",
    points: 30,
    isSpecial: false,
    superPower: "Análise de Variância",
    achievement: "Automatizou 15 relatórios manuais com Power BI",
    curiosity: "Maratonista e triatleta nos fins de semana",
  },
  {
    name: "Marcelo Souza",
    role: "Especialista em Normas Contábeis",
    area: "Controladoria",
    management: "Finanças Corporativas",
    yearsAtVale: 7,
    rarity: "rara",
    category: "Guardiões da Controladoria",
    points: 35,
    isSpecial: false,
    superPower: "Domínio do IFRS",
    achievement: "Implementou IFRS 16 em toda a empresa",
    curiosity: "Já leu todos os pronunciamentos do IASB na íntegra",
  },
  {
    name: "Patrícia Rocha",
    role: "Analista Júnior de Custos",
    area: "Controladoria",
    management: "Finanças Corporativas",
    yearsAtVale: 2,
    rarity: "comum",
    category: "Guardiões da Controladoria",
    points: 10,
    isSpecial: false,
    superPower: "Aprendizado Acelerado",
    achievement: "Aprovada em CPA-20 no primeiro mês de empresa",
    curiosity: "Toca violino em uma orquestra amadora",
  },
  // ── Heróis do Orçamento ────────────────────────────────────────────────────
  {
    name: "Eduardo Pires",
    role: "Gerente de Planejamento Financeiro",
    area: "FP&A",
    management: "Finanças Corporativas",
    yearsAtVale: 11,
    rarity: "epica",
    category: "Heróis do Orçamento",
    points: 55,
    isSpecial: false,
    superPower: "Previsão Precisa",
    achievement: "Modelo de forecast com 98% de acuracidade",
    curiosity: "Campeão de xadrez do Rio de Janeiro em 2015",
  },
  {
    name: "Camila Ferreira",
    role: "Analista de FP&A",
    area: "FP&A",
    management: "Finanças Corporativas",
    yearsAtVale: 5,
    rarity: "rara",
    category: "Heróis do Orçamento",
    points: 30,
    isSpecial: false,
    superPower: "Business Intelligence",
    achievement: "Criou o painel de KPIs usado por toda a diretoria",
    curiosity: "Já visitou 30 países em viagens de mochila",
  },
  {
    name: "Thiago Martins",
    role: "Analista de Orçamento",
    area: "FP&A",
    management: "Finanças Corporativas",
    yearsAtVale: 3,
    rarity: "comum",
    category: "Heróis do Orçamento",
    points: 15,
    isSpecial: false,
    superPower: "Excel Avançado",
    achievement: "Desenvolveu macro que reduziu consolidação de 8h para 20min",
    curiosity: "Apicultor nas horas vagas",
  },
  // ── Rangers da Tesouraria ──────────────────────────────────────────────────
  {
    name: "Luciana Oliveira",
    role: "Especialista em Derivativos",
    area: "Tesouraria",
    management: "Finanças Corporativas",
    yearsAtVale: 10,
    rarity: "epica",
    category: "Rangers da Tesouraria",
    points: 60,
    isSpecial: false,
    superPower: "Proteção Cambial",
    achievement: "Estruturou estratégia de hedge para dólar e minério",
    curiosity: "Faz mergulho profissional e já encontrou um naufrágio",
  },
  {
    name: "Rafael Cardoso",
    role: "Analista de Captação",
    area: "Tesouraria",
    management: "Finanças Corporativas",
    yearsAtVale: 6,
    rarity: "rara",
    category: "Rangers da Tesouraria",
    points: 30,
    isSpecial: false,
    superPower: "Gestão de Dívida",
    achievement: "Participou de roadshow que captou US$2 bilhões",
    curiosity: "Sommelier certificado em vinhos e cervejas artesanais",
  },
  {
    name: "Daniela Neves",
    role: "Analista de Cash Management",
    area: "Tesouraria",
    management: "Finanças Corporativas",
    yearsAtVale: 3,
    rarity: "comum",
    category: "Rangers da Tesouraria",
    points: 10,
    isSpecial: false,
    superPower: "Fluxo de Caixa",
    achievement: "Automatizou conciliação bancária de 12 contas",
    curiosity: "Já correu cinco provas de mountain bike",
  },
  // ── Mestres da Tributação ──────────────────────────────────────────────────
  {
    name: "Silvio Gomes",
    role: "Gerente de Tributos",
    area: "Tributário",
    management: "Finanças Corporativas",
    yearsAtVale: 15,
    rarity: "epica",
    category: "Mestres da Tributação",
    points: 65,
    isSpecial: false,
    superPower: "Planejamento Tributário",
    achievement: "Obteve crédito tributário de R$1,2 bilhão para a empresa",
    curiosity: "Professor universitário de Direito Tributário nas noites",
  },
  {
    name: "Amanda Castro",
    role: "Advogada Tributária",
    area: "Tributário",
    management: "Finanças Corporativas",
    yearsAtVale: 8,
    rarity: "rara",
    category: "Mestres da Tributação",
    points: 35,
    isSpecial: false,
    superPower: "Contencioso Fiscal",
    achievement: "Ganhou disputas tributárias de R$800M no CARF",
    curiosity: "Escreveu um livro sobre tributação de royalties",
  },
  {
    name: "Bruno Teixeira",
    role: "Analista Tributário",
    area: "Tributário",
    management: "Finanças Corporativas",
    yearsAtVale: 2,
    rarity: "comum",
    category: "Mestres da Tributação",
    points: 10,
    isSpecial: false,
    superPower: "SPED e Obrigações Acessórias",
    achievement: "Transmitiu EFD-REINF sem apontamento no primeiro ano",
    curiosity: "Campista de fim de semana em todos os biomas brasileiros",
  },
  // ── Visionários de RI ──────────────────────────────────────────────────────
  {
    name: "Viviane Barros",
    role: "Diretora de Relações com Investidores",
    area: "Relações com Investidores",
    management: "Alta Gestão",
    yearsAtVale: 13,
    rarity: "lendaria",
    category: "Visionários de RI",
    points: 120,
    isSpecial: false,
    superPower: "Comunicação Estratégica",
    achievement: "Liderou IPO secundário mais bem-sucedido da Bolsa",
    curiosity: "Já apresentou em conferências em Nova York, Londres e Tóquio",
  },
  {
    name: "Henrique Fonseca",
    role: "Gerente de RI",
    area: "Relações com Investidores",
    management: "Alta Gestão",
    yearsAtVale: 9,
    rarity: "epica",
    category: "Visionários de RI",
    points: 55,
    isSpecial: false,
    superPower: "Análise de Mercado de Capitais",
    achievement: "Ganhou prêmio de melhor RI do setor de mineração",
    curiosity: "Corredor de maratona com três sub-4 horas",
  },
  {
    name: "Lara Monteiro",
    role: "Analista de RI",
    area: "Relações com Investidores",
    management: "Alta Gestão",
    yearsAtVale: 4,
    rarity: "rara",
    category: "Visionários de RI",
    points: 30,
    isSpecial: false,
    superPower: "Earnings Release",
    achievement: "Coordenou teleconferência com mais de 500 investidores",
    curiosity: "Blogueira de finanças pessoais com 50 mil seguidores",
  },
  // ── Inovadores Digitais ────────────────────────────────────────────────────
  {
    name: "Renata Campos",
    role: "Gerente de Transformação Digital em Finanças",
    area: "Tecnologia Financeira",
    management: "Finanças Corporativas",
    yearsAtVale: 7,
    rarity: "epica",
    category: "Inovadores Digitais",
    points: 55,
    isSpecial: false,
    superPower: "Automação e RPA",
    achievement: "Liderou implantação de RPA que economizou 20 mil horas/ano",
    curiosity: "Desenvolve apps no tempo livre, já lançou dois na Play Store",
  },
  {
    name: "Felipe Araújo",
    role: "Cientista de Dados Financeiros",
    area: "Tecnologia Financeira",
    management: "Finanças Corporativas",
    yearsAtVale: 5,
    rarity: "rara",
    category: "Inovadores Digitais",
    points: 35,
    isSpecial: false,
    superPower: "Machine Learning Financeiro",
    achievement: "Modelo de ML que prevê inadimplência com 95% de acurácia",
    curiosity: "Contribuidor ativo em projetos open-source de IA",
  },
  {
    name: "Isabela Nunes",
    role: "Analista de Sistemas Financeiros",
    area: "Tecnologia Financeira",
    management: "Finanças Corporativas",
    yearsAtVale: 3,
    rarity: "comum",
    category: "Inovadores Digitais",
    points: 15,
    isSpecial: false,
    superPower: "SAP FI/CO",
    achievement: "Migrou módulo de pagamentos para SAP S/4HANA sem incidentes",
    curiosity: "Ceramista amadora e instrutora de yoga aos domingos",
  },
  // ── Compliance e Governança ────────────────────────────────────────────────
  {
    name: "Marcos Vidal",
    role: "Gerente de Compliance Financeiro",
    area: "Compliance",
    management: "Jurídico e Compliance",
    yearsAtVale: 14,
    rarity: "epica",
    category: "Compliance e Governança",
    points: 60,
    isSpecial: false,
    superPower: "Integridade Financeira",
    achievement: "Estruturou programa de compliance reconhecido internacionalmente",
    curiosity: "Já falou em três audiências no Congresso Nacional",
  },
  {
    name: "Tatiana Corrêa",
    role: "Analista de Controles Internos",
    area: "Compliance",
    management: "Jurídico e Compliance",
    yearsAtVale: 6,
    rarity: "rara",
    category: "Compliance e Governança",
    points: 30,
    isSpecial: false,
    superPower: "Mapeamento de Riscos",
    achievement: "Implementou matriz de riscos SOX para 120 processos",
    curiosity: "Fotógrafa de natureza e já publicou em revista nacional",
  },
  {
    name: "Anderson Lima",
    role: "Assistente de Auditoria Interna",
    area: "Compliance",
    management: "Jurídico e Compliance",
    yearsAtVale: 1,
    rarity: "comum",
    category: "Compliance e Governança",
    points: 10,
    isSpecial: false,
    superPower: "Due Diligence",
    achievement: "Primeira auditoria executada com recomendações aceitas 100%",
    curiosity: "Judoca faixa preta e treinador em escolinha local",
  },
  // ── Figurinhas Especiais ───────────────────────────────────────────────────
  {
    name: "Troféu Mestre do Álbum",
    role: "Conquista Especial",
    area: "Álbum",
    management: "Conquistas",
    rarity: "epica",
    category: "Especiais",
    points: 200,
    isSpecial: true,
    superPower: "Persistência",
    achievement: "Completou 80% do álbum Finanças Empresariais Legends 2026",
    curiosity: "Figurinha exclusiva para quem chegou perto do topo",
  },
  {
    name: "Troféu Campeão dos Legends",
    role: "Conquista Máxima",
    area: "Álbum",
    management: "Conquistas",
    rarity: "lendaria",
    category: "Especiais",
    points: 500,
    isSpecial: true,
    superPower: "Maestria Total",
    achievement: "Completou 100% do álbum Finanças Empresariais Legends 2026",
    curiosity: "Figurinha ultra-rara reservada ao verdadeiro Mestre do Álbum",
  },
];

async function main() {
  const [existing] = await db.select({ count: count() }).from(collaboratorsTable);
  if (Number(existing?.count ?? 0) > 0) {
    console.log(`Database already has ${existing?.count} collaborators. Skipping seed.`);
    process.exit(0);
  }

  console.log(`Seeding ${collaborators.length} collaborators...`);
  await db.insert(collaboratorsTable).values(collaborators);
  console.log("Done!");
  process.exit(0);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
